language: python
env:
  - TOXENV=py26
  - TOXENV=py27
  - TOXENV=py32
  - TOXENV=py33
  - TOXENV=py34
  - TOXENV=py35
  - TOXENV=flake8
  - TOXENV=cov
install:
  - pip install -r requirements.txt
  - pip install --quiet --use-mirrors tox
script:
  - tox
after_script:
  - if [ $TOXENV == "cov" ]; then
    pip install --quiet --use-mirrors coveralls;
    coveralls;
    fi
